[package]
name = "sysctl"
version = "0.1.4"
authors = ["Johannes Lundberg <johalun0@gmail.com>", "Ivan Temchenko <ivan.temchenko@yandex.ua>"]
description = "Simplified interface to libc::sysctl"
keywords = ["sysctl", "freebsd", "macos"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/johalun/sysctl-rs"
documentation = "https://johalun.github.io/sysctl-rs/sysctl/index.html"

[dependencies]
libc = "^0.2.34"
byteorder = "^1.0.0"
errno = "^0.2.3"

